<section class="content" ng-controller="admin_support_index_view">

    <?php
    //require_once ("application/block/default_index.php");

    use Base\ModelBase;
    use Base\ClassRoute;
    //die();
    ?>
    <link rel="stylesheet" href="<?php echo ClassRoute::getTemplateUri(); ?>/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="/public/jQuery-contextMenu/jquery.contextMenu.css">
    <link href="/public/css/lad-tree/lad-tree.css" rel="stylesheet">


    <script src="/public/jQuery-contextMenu/jquery.contextMenu.js"></script>



    <div ng-app="ladApp" ng-controller="TreeController" id="tree_in_index_browse">
        <?php require_once "application/block/tree_block_tplAddTo.php"?>

        <script type="text/ng-template" id="tplTreeModalSelectFolder">
            <span style="" ng-click="toggleNodeLeft(menu.id, 0, 1)">
        <i style="margin: 0 5px" ng-show="menu.menus" class="fa fa-angle-down" aria-hidden="true"></i>
        <i style="margin: 0 5px" ng-show="!menu.menus" class="fa fa-caret-right" aria-hidden="true"></i>
    </span>
            <button style="border: 0px solid gray; background-color: transparent; overflow: hidden" id="folderToMove-{{menu.id}}"
                    onclick="ClassTree.choiceFolderToMove(event)"
                    onmouseup="ClassTree.hoverFolderToMove(event)"
                    ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
                    title="{{menu.name}}">
                <i style="color: #6B8E23;" id="folderToMove2-{{menu.id}}" class="fa fa-folder" aria-hidden="true"
                   onclick="ClassTree.choiceFolderToMove(event)"
                   onmouseup="ClassTree.hoverFolderToMove(event)"
                   ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
                   title="{{menu.name}}"></i>
                {{menu.name|limitTo:20}}{{menu.name.length > 20? "..." : ""}}

                <a href="/{{_module}}/{{_controller}}/{{_action}}/folder/{{menu.id.replace('folder_','')}}"> [browse] </a>

            </button>

            <ul  ng-if="menu.menus">
                <li ng-repeat="menu in menu.menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
                </li>
            </ul>
        </script>


        <!-- Modal Popup Add to folder-->
        <div class="modal" id="myModalTreeSelectFolder" tabindex="-1" role="dialog" aria-labelledby="myModalTreeLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalTreeLabel">Chọn folder duyệt</h4>
                    </div>
                    <div class="modal-body">
                        <ul><a href="/{{_module}}/{{_controller}}/{{_action}}"> DUYỆT TẤT CẢ </a>
                            <li ng-repeat="menu in menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
                            </li>
                        </ul>
                    </div>
                    <div class="modal-footer">

                        <!--                    <input type="text" class="form-control" style="float: left; width: 150px; margin: 0px 5px;">-->
                        <!---->
                        <!--                    <button type="button" class="btn btn-success" style="float: left;">Tạo Folder</button>-->

                        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

    </div>



    <!--  Old delete:  Modal Popup Add/Edit item-->
    <div class="modal-dialog" id="edit_item" style="display: none">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" ng-click="showEditDialog(false)">
                    <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Add/Edit item</h4>
            </div>
            <div class="modal-body">
                <div  ng-repeat="meta in meta_data">
                    <label ng-model="meta.name"> {{meta.name}} </label>
                    <input ng-show="meta.editable" type="text" class="form-control" ng-model="editingItem[meta.field]">
                    <input ng-show="!meta.editable" type="text" readonly class="form-control" ng-model="editingItem[meta.field]">
                </div>
                <span id="status_edit_del" style="color: brown;"> </span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" ng-click="showEditDialog(false)">Close</button>
                <button type="button" class="btn btn-primary" ng-click="saveItem()" ng-show="!isEmpty(arrEditable)">Save</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->


    <!-- New : View/Edit Modal -->
    <div class="modal" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Add/Edit item</h4>
                </div>
                <div class="modal-body">

                    <div  ng-repeat="meta in meta_data" >
                        <label ng-model="meta.name"> {{meta.name}} </label>
                        <!--                        <input ng-show="meta.editable" type="text" class="form-control" ng-model="editingItem[meta.field]">-->
                        <!--                        <input ng-show="!meta.editable" type="text" readonly class="form-control" ng-model="editingItem[meta.field]">-->

                        <input ng-show="!meta.is_status && meta.editable" type="text" class="form-control" ng-model="editingItem[meta.field]">
                        <input ng-show="!meta.is_status && !meta.editable" type="text" readonly class="form-control" ng-model="editingItem[meta.field]">
                        <input ng-show="meta.is_status" type="checkbox" ng-click="changeStatusValue($event, meta.field)"
                               ng-checked="editingItem[meta.field] == 1" ng-disabled="!meta.editable">

                    </div>
                    <span id="status_edit" style="color: brown;"> </span>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" ng-click="showEditDialog(false)">Close</button>
                    <button type="button" class="btn btn-primary" ng-click="saveItem()" ng-show="!isEmpty(arrEditable)">Save</button>
                </div>
            </div>
        </div>
    </div>


    <div class="box" ng-cloak>
        <!-- /.box-header -->
        <div class="box-body">
            <?php
            //echo $controller = \Base\ClassRoute::$controller;

            $module = ClassRoute::$module;
            $controller = ClassRoute::$controller;
            $uri  = "/$module/$controller";
            //$listUri = str_replace("-index", '-tree', $uri);
            $listUri = str_replace("-index", '-tree', $uri);
            //echo "<br/> $listUri";
            ?>

            <div style="padding: 3px; float: right; font-size: smaller" ng-show="indexHasTree"><a href="<?php echo $listUri ?>"> <button>TreeView</button>  </a> </div>
            <div class="dataTables_wrapper form-inline dt-bootstrap" >
                <div ng-show="hasDeleteDate">
                    Custom filter:  <input type="checkbox" style="color: red" ng-model="filter_delete_only" ng-click="filter_delete_only_click($event)"> List delete Only
                </div>

                <!-- Limit per page-->
                <div class="row" >
                    <div class="col-sm-2" ng-show="true">
                        <label>
                            Show
                            <select ng-change="selectNumberItem()" ng-model="number_item_per_page" name="example1_length" aria-controls="example1" class="form-control input-sm">
                                <option value="5" ng-selected="{{number_item_per_page == 5}}">5</option>
                                <!--                                <option value="6" ng-selected="{{number_item_per_page == 6}}">6</option>-->
                                <option value="10" ng-selected="{{number_item_per_page == 10}}">10</option>
                                <option value="25" ng-selected="{{number_item_per_page == 25}}">25</option>
                                <option value="50" ng-selected="{{number_item_per_page == 50}}">50</option>
                                <option value="100" ng-selected="{{number_item_per_page == 100}}">100</option>
                            </select>
                        </label>
                    </div>
                    <!--  Search Zone-->
                    <div class="col-sm-10">
                        <!--  Spec Filter-->
                        <div ng-show="search_spec_filter" style="float: left; border: 0px solid gray; margin: 1px; padding: 0px 0px">
                            <!--                            <b style="float: left">Spec filter: </b>-->
                            <!--                    {{spec_filter}}-->
                            <div ng-repeat="(filterName, arrInfo) in search_spec_filter" style="border: 1px solid #ccc; padding: 1px 2px; float: left; margin-right: 3px">
                                <!--                        - key/arrInfo = {{key}} : {{arrInfo}} ,-->
                                <span ng-show="arrInfo[1] == 'boolean'">
                                    <input type="checkbox" id="filter_check_{{filterName}}" ng-model="search_spec_filter_value[filterName]"> <label style="font-weight: normal" for="filter_check_{{filterName}}"> {{arrInfo[0]}} </label>
                                </span>

                                <span ng-show="arrInfo[1] == 'text'">
                                    {{arrInfo[0]}} : <input type="text" ng-model="search_spec_filter_value[filterName]">
                                </span>
                            </div>
                            <!--                    <button ng-click="testok()"> TESTOK</button>-->
                        </div>

                        <!--  Default search-->
                        <div ng-repeat="meta in meta_data" ng-if="meta.searchable" class="admin_search_able" style="float: left; margin: 1px">
                            <input style="color:red" class="admin_search_field" type="search" ng-enter="searchField()" ng-model="search_field[meta.field]" placeholder="Tìm {{meta.name}}" aria-controls="">
                        </div>
                        <div style="float: left; margin: 1px">
                            <button ng-show="countSearchField > 0" class="admin_search_button"  type="submit" ng-click="searchField()" >Tìm</button>
                        </div>
                        <div style="float: left; margin: 1px">
                            <button style="background-color: darkred; color: white" class="admin_search_cancel" type="submit" ng-click="searchFieldCancel()"
                                    ng-show="!isEmpty(search_spec_filter_value) || !isEmpty(search_field) || filter_delete_only == true" >Hủy</button>
                        </div>
                    </div>

                </div>

                <p style="position:fixed;left: 50%;z-index: 10000" ng-hide="dataLoaded">
                    <i class="fa fa-spinner fa-spin fa-2x"></i>
                </p>

                <!--Paginator-->
                <div class="row" ng-show="true">


                    <div class="col-sm-5" ng-show="true">
                        <div class="dataTables_info" role="status" aria-live="polite">Showing <b>{{fromItem}}</b> to <b>{{toItem}}</b> of <b>{{totalRow}}</b> entries </div>

                        <a ng-show="indexHasTree" title="select folder to browse" style="padding: 0px 3px; background-color: darkgray; border 1px solid green" href="#"
                           onclick="$('#myModalTreeSelectFolder').modal('show')">Folder <i class="fa fa-caret-right" aria-hidden="true"></i></a>

                        <span ng-repeat="item in parent_path" > <a href="/{{_module}}/{{_controller}}/{{_action}}/folder/{{item.id}}">{{item.name }}</a>
                        <i class="fa fa-caret-right" aria-hidden="true"></i> </span>
                    </div>

                    <div class="col-sm-7" ng-show="info_data.nPage > 1">
                        <div class="dataTables_paginate paging_simple_numbers">
                            <ul class="pagination">
                                <li  ng-repeat="page in arrPage" class="{{page.class}} ">
                                    <!--                                    <a ng-click="getDataList(page.page_number)" >{{page.name}}</a>-->
                                    <a href="#" ng-click="page.link!='#' ? getDataList(page.page_number) : ''" >{{page.name}}</a>
                                    <!--                                    <button ng-click="getDataList(page.page_number)"> {{page.name}}</button>-->
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>

                <!--Data Table-->
                <div style="overflow: auto;overflow-y: hidden;">
                    <table class="table table-bordered table-striped dataTable"
                           role="grid" aria-describedby="example1_info">

                        <!--table header-->
                        <thead>
                        <tr role="row">
                            <th>STT</th>
                            <!--                            <th style="display: {{batch_command ? '': 'none'}}"><input type="checkbox" ng-click="checkAllItem($event)"> </th>-->
                            <!--                            <th style="text-align: center; color: #0a6aa1;" ng-show="true">-->
                            <!--                                <i ng-show="!isEmpty(arrEditable)" title="Add Item" class="fa fa-plus-square fa-2x" aria-hidden="true" ng-click="!isEmpty(arrEditable) && showEditDialog(true, null)" ></i>-->
                            <!--                                <span ng-show="isEmpty(arrEditable)"> Action </span>-->
                            <!--                            </th>-->
                            <th ng-repeat="meta in meta_data" ng-if="meta.show_in_index" >
                                <span ng-show=" !meta.sortable"> {{meta.name}} </span>
                                <a title="click to sort" ng-show="meta.sortable" href="" ng-click="sortWithField(meta.field)">{{meta.name}}
                                    <i ng-show="meta.sortType == 'asc' || meta.sortType == 'desc'"
                                       class="fa {{meta.sortType == 'desc' ? 'fa-sort-alpha-desc' :  'fa-sort-alpha-asc'}} " aria-hidden="true"></i>
                                </a>
                                <i ng-click="stopSort()" title="cancel sort" style="margin-left: 5px; color: brown" ng-show="meta.sortType == 'asc' || meta.sortType == 'desc'" class="fa fa-times" aria-hidden="true"></i>
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        <!--table content-->
                        <tr ng-repeat="record in arr_data">
                            <td>{{ (currentPage - 1) * number_item_per_page + $index + 1}}</td>
                            <!--                            <td  style="display: {{batch_command ? '': 'none'}}"><input type="checkbox" ng-model="arr_data[$index]._checkBox" ng-click="checkItem($index)"> </td>-->
                            <!--                            -->
                            <!--                            <td style=" text-align: center; color: #0a6aa1;"  ng-show="true">-->
                            <!---->
                            <!---->
                            <!--                                <i title="AddToTree" ng-show="indexHasTree" ng-click="addToMultiFolder_(record.id)" class="fa fa-tree fa-2x" aria-hidden="true"  style="color: lightslategray"></i>-->
                            <!---->
                            <!--                                <i title="Edit" ng-click="showEditDialog(true, record)" class="fa fa-pencil-square-o fa-2x" aria-hidden="true"  style="color: lightslategray"></i>-->
                            <!--                                <i title="delete" ng-click="deleteItem($index)" ng-show="record['delete_date'] == ''" class="fa fa-trash fa-2x" aria-hidden="true" style="color: lightslategray"></i>-->
                            <!--                                <i title="Un Delete" ng-click="unDeleteItem($index)" ng-show="record['delete_date'] > ''" class="fa fa-undo fa-2x" aria-hidden="true" style="color: lightslategray"></i>-->
                            <!--                            </td>-->
                            <td ng-repeat="(field, value) in record" ng-if="field.substring(0,1)!='_' && arrShowInIndex[field]"> <!-- Ignore added controller field start with _ -->

                                <i ng-show="arrEditable[field] && record._editThisField != field && !arrIsStatus[field]" ng-click="editField($parent.$parent.$index, field)"  class="fa fa-pencil-square-o" aria-hidden="true" title="edit"></i>

                                <span style="color: {{field == 'delete_date' ? 'red':''}}" ng-show="record._editThisField != field && !arrIsStatus[field]"
                                      title="{{arr_data[$parent.$parent.$index][field]}}">
                                    <span ng-show="!meta_data_with_field[field]['link_to_view']">
                                        {{arr_data[$parent.$parent.$index][field]|limitTo:20}}{{arr_data[$parent.$parent.$index][field].length > 20? "..." : ""}}
                                     </span>
                                    <span ng-show="meta_data_with_field[field]['link_to_view']">
                                        <a href="/{{_module}}/{{_controller}}/view/{{field}}/{{arr_data[$parent.$parent.$index].id}}">
                                        {{arr_data[$parent.$parent.$index][field]|limitTo:20}}{{arr_data[$parent.$parent.$index][field].length > 20? "..." : ""}}
                                            <br>
                                            <div style="font-style: italic; color: white; border: 0px solid brown; font-size: smaller; background-color: orange; padding: 1px 5px 2px 3px; border-radius: 5px"
                                                  ng-show="arr_data[$parent.$parent.$index]['_need_admin_reply'] == 1">
                                            need admin reply
                                        </div>

                                        </a>


                                     </span>
                                </span>


                                <i ng-click="saveField($parent.$parent.$index, field, value)"  ng-show="record._editThisField == field"  class="fa fa-floppy-o" aria-hidden="true" title="save"></i>
                                <i ng-click="cancelEditField($parent.$parent.$index, field)"  ng-show="record._editThisField == field"  class="fa fa-ban" aria-hidden="true" title="cancel"></i>
                                <!--                                    ui-keydown="{esc: 'keyCallback($event)'}"-->
                                <input id="inp_{{$parent.$parent.$index}}_{{field}}" ng-show="record._editThisField == field"
                                       ng-esc="cancelEditField($parent.$parent.$index, field)" ng-enter="saveField($parent.$parent.$index, field, value)"
                                       type="text" class="form-control" ng-model="arr_data[$parent.$parent.$index][field]" style="">


                                <span ng-show="meta_data_with_field[field]['is_status'] && !meta_data_with_field[field]['status_icon_extra']">
                                    <i ng-click="arrEditable[field] && changeStatus($parent.$parent.$index, field)"
                                       class="{{arr_data[$parent.$parent.$index][field] == 1 ? 'fa fa-toggle-on fa-2x': 'fa fa-toggle-off fa-2x'}}"
                                       style="color: #0a6aa1" aria-hidden="true"></i>
                                </span>
                                <span ng-show="meta_data_with_field[field]['is_status'] && meta_data_with_field[field]['status_icon_extra']">
                                    <i ng-click="arrEditable[field] && changeStatus($parent.$parent.$index, field)"
                                       class="{{meta_data_with_field[field]['status_icon_extra']}}"
                                       style="{{arr_data[$parent.$parent.$index][field] == 1 ? 'color: red' : 'color: blue' }}" aria-hidden="true"></i>
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                </div>
                <select  style="display: {{batch_command ? '': 'none'}}" ng-model="selectCommandName">
                    <option ng-repeat="command in batch_command" value="{{command.command}}">{{command.name}}</option>
                </select>
                <button  style="display: {{batch_command ? '': 'none'}}" ng-click="runCommand()"> Thực hiện </button>

                <!--Paginator-->
                <div class="row" ng-show="info_data.nPage > 1">
                    <div class="col-sm-5">
                        <div class="dataTables_info" role="status" aria-live="polite">Showing {{fromItem}} to {{toItem}} of {{totalRow}} entries</div>
                    </div>
                    <div class="col-sm-7">
                        <div class="dataTables_paginate paging_simple_numbers">
                            <ul class="pagination">
                                <li  ng-repeat="page in arrPage" class="{{page.class}} ">
                                    <a href="#" ng-click="getDataList(page.page_number)" >{{page.name}}</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <!-- /.content -->
    <!-- Main content -->

</section>



