<br>
<br>

DEMO_MODAL

https://getbootstrap.com/docs/3.3/javascript
<a href="https://getbootstrap.com/docs/3.3/javascript/">https://getbootstrap.com/docs/3.3/javascript/</a>

<br>


<button onclick="document.getElementById('modal_id_lad1').style.display='block'">Open Modal LAD </button>

<br>
abc123
<br>
abc123
<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123
<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123
<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123
<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123
<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123<br>abc123

<br>

<div class="modal_lad2">
    <div id="modal_id_lad1" class="modal2">

        <div class="modal-content">
            <div class="container_modal">
                <b>Delete Account</b>

                <span onclick="document.getElementById('modal_id_lad1').style.display='none'" class="close" title="Close Modal">×</span>

                <p>Are you sure you want to delete your account?</p>
                <p>Are you sure you want to delete your account?</p>
                <p>Are you sure you want to delete your account?</p>

                <div style="color: red; border: 1px solid gray" onclick="addLine(this)"> Click this To Add Line to see V-Scrool </div>


                <div class="clearfix">
                    <button type="button" onclick="document.getElementById('modal_id_lad1').style.display='none'" class="cancelbtn">Cancel</button>
                    <button type="button" onclick="document.getElementById('modal_id_lad1').style.display='none'" class="deletebtn">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>



<br>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM

                <br>
                Nhập vào ABC: <input class="form-control" type="text" value="" placeholder="test123">

                <br>
                Nhập vào 123: <input class="form-control" type="text" value="" placeholder="test456">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script>

    setTimeout(function () {
        $("#myModal").modal("show");
    },500);



    function addLine(ev) {

        ev.innerHTML = ev.innerHTML + " <br/> abc ";
    }


</script>