<?php

$link = ctoolUrl::getUriWithoutParam();

$params = \Base\ClassRoute::getArrParams();
$paramsPost = $_POST;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        NewsListMongo-List
        <small> <a href="/admin/news-index/index-mg">Index</a> </small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <?php

            $pad = '';
            if(isset($params['delete_list']))
                $pad = "style = 'color: red; font-size: 30px'";

            echo "<a $pad href='$link?delete_list=1' class='fa fa-2x fa-trash'>  </a> ";
            ?>
        </li>
    </ol>

</section>

<?php


//Table setting
clsDbTableMng::$gidCurrent = getCurrentGid();
clsDbTableMng::$class = modelNewsFile2::class;
clsDbTableMng::setAllowAddButton(1);
clsDbTableMng::setAllowSaveButtonOnEdit(1);
clsDbTableMng::setUrlEditActionInList("/admin/news-index/view-mg");
clsDbTableMng::setUrlApi("/a_p_i/admin-news-mg-list");
clsDbTableMng::setShowDeleteButtonInList(1);
clsDbTableMng::$optShowSearchButtonInList = 1;
clsDbTableMng::$optExtraActionCallBack = 'callBackMoveItemAction';
clsDbTableMng::$optAddNewUrl = '/admin/news-index/add-mg';

//Tree Setting
clsTreeMng::$classFile = modelNewsFile2::class;
clsTreeMng::$classFolder = modelNewsFolder2::class;

$obj1 = new clsDbTableMng::$class;
if ($obj1 instanceof \Base\modelBaseMongo) ;

?>
<!-- Main content -->
<section class="content">

    <?php

    //$apiUrl = "/a_p_i/admin/mng-db-table?modelDb=" . urlencode(clsDbTableMng::$class);
    echo "<div style='width: 20%; float: left'>";
    clsTreeMng::showMoveModals();
    clsTreeMng::showTree();
    echo "</div>";

    echo "<div style='padding: 0px 5px; float: left; width: 80%'>";

    clsDbTableMng::getInsertFormPost();

    if (isset($params['insert_item'])) {

        echo "<br/>\n";
        clsDbTableMng::showInsertForm();
        echo "<br/>\n";
        goto _END;
    }

    if (isset($params['edit_item'])) {
        echo "<br/>\n";
        clsDbTableMng::showEditForm();
        echo "<br/>\n";
        goto _END;
    }

    //$obj1 = new modelDemo1Mongo();
    if (!ctoolUrl::getParamInUrl('meta_mng')) {
        clsDbTableMng::getFilterSearchUI();
        echo "<br/>\n";
    }

    clsDbTableMng::showTableData1();

    echo "</div>";

    _END:
    ?>

    <div style="clear: both"></div>

</section>
<!-- /.content -->
<!-- Main content -->

<script>
   clsDataTblMng.apiUrl = '<?php   echo  clsDbTableMng::getUrlApi();    ?>';
   clsTree.apiBase = '<?php   echo  clsDbTableMng::getUrlApi();    ?>';
   //clsTree.urlBase = '<?php echo ctoolUrl::getUriWithoutParam() ?>';

</script>

