

<section class="content">
    DataIndex2
    <?php

    //    $obj = new modelDataFile2();
    //    $obj->createMetaTable();

    $obj = new \Base\ModelDataFile();
    $obj->createMetaTable();

//    echo "<br/>\nMetaTable: " . $obj->getMetaInfoTable();

    $mt = $obj->getMetaDataApi();

    clsDbTableMng::$class = \Base\ModelDataFile::class;
    clsDbTableMng::$gidCurrent = 1;
    clsDbTableMng::$optUrlEditActionInList = "/admin/data-index/view2";
    clsDbTableMng::$optAddNewUrl = '/admin/data-index/add2';
    //$obj->getNameDescFromField('1');

    clsDbTableMng::getFilterSearchUI();



    clsDbTableMng::showTableData1();

    ?>

</section>

<script>

    clsDataTblMng.apiUrl = '/a_p_i/member-data';

</script>

