
<?php
\Base\ClassUploadSetting::$moduleUploadNow = 'image#';
\Base\ClassUploadSetting::$getStaticLinkAfterUpload = 1;
require_once (\Base\ClassRoute::$rootDirApp."/application/block/upload_block.php");

$module = \Base\ClassRoute::getCurrentModule();
$controller = \Base\ClassRoute::getCurrentController();
$action = \Base\ClassRoute::getCurrentAction();
$strToSaveSession = str_replace("-","_", $module.$controller.$action);

$params = \Base\ClassRoute::getArrParams();

if(isset($params['id'])){
    $idRand = $params['id'];
    $id = qqgetIdFromRand($params['id']);
    if(!is_numeric($id)){
        loi("Not valid id?");
    }

    //bl("ID = $id");

    $obj = new \Base\ModelDataFile();
    if(!$obj->getOne($id)){
        bl("Không tồn tại id này? $idRand");
        return;
    }
}
if(isset($params['create_new'])){
    $obj = new \Base\ModelDataFile();
    $obj->initEmptyObject();
}

?>

<script>
    //    var urlBaseApiTree = "/a_p_i/member-image";// ?time=1516245801505&pid=folder_0
    //    var modulePublicTree = "image";
    //    var viewAsDefaultGridOrTable = 'grid'; //'table'

    function doneUploadFile(data) {
        //alert("Upload done!");

        console.log(" doneUploadFile data = " + JSON.stringify(data.payload));

        if(!ClassApi.checkReturnApi(data)){
            alert("Not valid return API after upload done? " + data);
            return;
        }
        console.log(" LINK IMG = " + data.payload[0].link_image_static);
        $("#img_zone").html($("#img_zone").html() + "<image style='width: 200px; margin: 3px; border: 1px solid darkslategray' src='" + data.payload[0].link_image_static + "'>");

    }

    setTimeout(function () {
        uploadObj.update({formData: {uploadModule: 'image_module_upload' }});
    }, 1000);
</script>




<div id="img_zone" style="border: 1px solid #ccc; padding: 2px">
    Image uploaded:
</div>


<br>
<a title="select folder to browse" style="padding: 3px 3px; background-color: darkgray; color: white;
 border 1px solid green" href="#" onclick="$('#myModalTreeSelectFolder').modal('show')"
   aria-hidden="false" class="">
    Select Folder <span id="selectingFolderPathToSave"><?php if($obj->id) echo $obj->getParentPathNames() ?></span>
    <i class="fa fa-caret-right" aria-hidden="true"></i>
</a>

<div ng-app="ladApp" ng-controller="TreeController" id="tree_in_index_browse">

    <script type="text/ng-template" id="tplTreeModalSelectFolder">
        <span style="" ng-click="toggleNodeLeft(menu.id, 0, 1)">
            <i style="margin: 0 5px" ng-show="menu.menus" class="fa fa-angle-down" aria-hidden="true"></i>
            <i style="margin: 0 5px" ng-show="!menu.menus" class="fa fa-caret-right" aria-hidden="true"></i>
        </span>
        <button style="border: 0px solid gray; background-color: transparent; overflow: hidden" id="folderToMove-{{menu.id}}"
                onclick="ClassTree.choiceFolderToMove(event)"
                onmouseup="ClassTree.hoverFolderToMove(event)"
                ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
                title="{{menu.name}}">
            <i style="color: #6B8E23;" id="folderToMove2-{{menu.id}}" class="fa fa-folder" aria-hidden="true"
               onclick="ClassTree.choiceFolderToMove(event)"
               onmouseup="ClassTree.hoverFolderToMove(event)"
               ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
               title="{{menu.name}}"></i>
            {{menu.name|limitTo:20}}{{menu.name.length > 20? "..." : ""}}
        </button>
        <span ng-click="selectFolderTree(menu.id)" style="background-color: gray; color: white; padding: 3px; margin: 1px"> select </span>

        <ul  ng-if="menu.menus">
            <li ng-repeat="menu in menu.menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
            </li>
        </ul>
    </script>


    <!-- Modal Popup Add to folder-->
    <div class="modal" id="myModalTreeSelectFolder" tabindex="-1" role="dialog" aria-labelledby="myModalTreeLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalTreeLabel">Chọn folder save Item</h4>
                </div>
                <div class="modal-body">

                    <ul>
<!--                        <a href="/{{_module}}/{{_controller}}/{{_action}}"> DUYỆT TẤT CẢ </a>-->

                        <li ng-repeat="menu in menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">

                    <!--                    <input type="text" class="form-control" style="float: left; width: 150px; margin: 0px 5px;">-->
                    <!---->
                    <!--                    <button type="button" class="btn btn-success" style="float: left;">Tạo Folder</button>-->

                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

</div>


<script>

    var urlBaseApiTree = '/a_p_i/member-data/list-tree-folder';

    setTimeout(function () {

        var scope = angular.element($("#tree_in_index_browse")).scope();
        if(!scope || typeof scope == 'undefined'){
            alert("Error: can not get scope?");
        }
        scope.selectFolderTree = function (id) {
            //alert("ID = " + id );
            // Simple GET request example:

            showWaittingIcon();

            var urlGet = "/a_p_i/member-data/get-item/id/" + id + "/filetype/0";
            $.get(urlGet, function(data, status){
                //alert("Data: " + data + "\nStatus: " + status);
                hideWaittingIcon();

                if(!ClassApi.checkReturnApi(data, urlGet))
                    return;

                ClassSettingApp.folderToSaveItem = id;

                console.log(" data = " + JSON.stringify(data));
                console.log(" data.payload._parent_path = " + data.payload._parent_path);

                $("#selectingFolderPathToSave").html(data.payload._parent_path);

                $('#myModalTreeSelectFolder').modal('hide');

                sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_id" ?> = id;
                sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?> = data.payload._parent_path;

            });
        }


        <?php
        //Neu la create new thì chọn sẵn folder đã chọn trước đó:
        if(isset($params['create_new'])){
        ?>
            if(sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?>){
                $("#selectingFolderPathToSave").html(sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?>);
                ClassSettingApp.folderToSaveItem = sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_id" ?>;
            }
        <?php
        }
        ?>

    }, 1000);
    ////
</script>


<?php

    $arrEdit = $obj->getArrayEditable();

//    echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//    print_r($arrEdit);
//    echo "</pre>";

if(isAdmin_()){


//    $arr1 = $obj->getMetaDataApi();
//    echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//    print_r($arr1);
//    echo "</pre>";





}

    echo "<br/><div style='float: left; max-width: 600px; padding : 10px'>";

    echo "<table class='glx03'>";
    foreach ($arrEdit as $field) {
        if(!in_array("$field", ['summary0','summary1','content','parent'])) {
            $val = $obj->$field;
            echo "<tr>";
            $fieldU = strtoupper($field);

            if(isset($params['create_new'])){
                if($field == 'price' || $field == 'status')
                    $val = 0;
                if($field == 'name'){
                    $val = 'new';
                }
            }

            if($obj->isStatusField($field)) {
                $padCheck = '';
                if($obj->$field)
                    $padCheck = 'checked';
                echo "<td>$fieldU: </td> <td style=''><input onclick='checkStatus_(event)' $padCheck type='checkbox'  id='edit_$field' value='$val'></td>";
            }
            else
                echo "<td>$fieldU: </td> <td><input style='width: 400px' class='form-control' id='edit_$field' value='$val' title='$val'></td>";

            echo "</tr>";
        }
        else{

        }
    }

    echo "</table>";

    echo "</div>";


?>


    <div class='div_img_data'>
        Img0 (Ảnh đại diện)
        <br>
    <img class="img_data" src="<?php echo $obj->image0 ?>">
    </div>

    <div class='div_img_data'>
    Img1<br>
    <img class="img_data"   src="<?php echo $obj->image1 ?>">
    </div>

    <div class='div_img_data'>
    Img2<br>
    <img class="img_data"   src="<?php echo $obj->image2 ?>">
    </div>

    <div class='div_img_data'>
    Img3<br>
    <img class="img_data"   src="<?php echo $obj->image3 ?>">
    </div>

    <div class='div_img_data'>
    Img4<br>
    <img class="img_data"   src="<?php echo $obj->image4 ?>">
    </div>

    <div class='div_img_data'>
    Img5<br>
    <img class="img_data"   src="<?php echo $obj->image5 ?>">
    </div>

    <div class='div_img_data'>
    Img6<br>
    <img class="img_data"   src="<?php echo $obj->image6 ?>">
    </div>



<div class="clearfix"></div>
<br>

<span style="font-size: 16px; font-weight: bold"> - Summary0: </span>
<textarea style="height: 100px" cols="70" rows="6" id="summary0" name="summary0"><?php echo $obj->summary0; ?></textarea>
<br>

<span style="font-size: 16px; font-weight: bold"> - Summary1: </span>
<textarea cols="80" id="summary1" name="summary1"><?php echo $obj->summary1; ?></textarea>
<br>

<span style="font-size: 16px; font-weight: bold"> - Summary2: </span>

<textarea cols="80" id="summary2" name="summary2"><?php echo $obj->summary2; ?></textarea>
<br>

<span style="font-size: 20px; font-weight: bold; color: red"> - Content: </span>
<textarea cols="80" id="content" name="content"><?php echo $obj->content; ?></textarea>

<?php
require_once "application/block/upload_image_clipboard.php";
require_once "application/block/waitting_icon.php";

?>



<script>
    CKEDITOR.replace('summary0');
    CKEDITOR.replace('summary1');
    CKEDITOR.replace('summary2');
    CKEDITOR.replace('content');

    CKEDITOR.autoGrow_onStartup = false;
    CKEDITOR.resize_enabled = false;

    CKEDITOR.config.enterMode = CKEDITOR.ENTER_BR;
    CKEDITOR.config.autoParagraph = false;
    //CKEDITOR.config.height = auto;
    CKEDITOR.config.width = 'auto';
    //CKEDITOR.config.width = 600;
    CKEDITOR.config.allowedContent = true;
    CKEDITOR.config.entities = false;
    CKEDITOR.config.entities_greek = false;
    CKEDITOR.config.entities_latin = false;
    //CKEDITOR.config.htmlEncodeOutput = false;
    CKEDITOR.dtd.$removeEmpty['i'] = false;
    //CKEDITOR.config.jsplus_include_css={'<?php echo \Base\ClassRoute::getBaseUri()?>/template/public1/css/bootstrap.css'};
    CKEDITOR.config.contentsCss = '<?php echo \Base\ClassRoute::getBaseUri()?>/template/public1/css/bootstrap.css';

    function saveData() {
//        alert("Save dataa");

        var data1 = {};
        <?php
            foreach ($arrEdit as $field) {
        ?>
                data1['<?php echo $field?>'] = $("#edit_" + '<?php echo $field?>').val();
        <?php
            }
        ?>

        var summary0 = CKEDITOR.instances['summary0'].getData();
        //var summary0 = $("#edit_summary0").val();
        var summary1 = CKEDITOR.instances['summary1'].getData();
        var summary2 = CKEDITOR.instances['summary2'].getData();
        var content = CKEDITOR.instances['content'].getData();

        data1['summary0'] = summary0;
        data1['summary1'] = summary1;
        data1['content'] = content;

        if(ClassSettingApp.folderToSaveItem)
            data1['parent'] = ClassSettingApp.folderToSaveItem;

        console.log(" DAA1 = " + JSON.stringify(data1));
        <?php
            if(isset($params['create_new'])){
        ?>
            var urlPost = '/a_p_i/member-data/add/';
        <?php
        }
        else{
        ?>
            var urlPost = '/a_p_i/member-data/save/?' + "&id=" + '<?php echo $obj->id ?>';
        <?php
        }
        ?>

        console.log(" urlPost Save = " + urlPost);

        showWaittingIcon();
        $.post(urlPost, data1, function(result){
            hideWaittingIcon();

            if(!ClassApi.checkReturnApi(result))
                return;
            if(result.payload == 0)
                showToastWarningBottom("Nothing update?");
            else
                showToastInfoBottom("Done?");

            <?php
            if(isset($params['create_new'])){
            ?>
                window.location.href = "<?php echo "/$module/$controller/view/id/" ?>" + result.payload;
            <?php
            }
            ?>
    });
}

function checkStatus_(e) {
    //alert("Check status..." + e.target.id);
    if($("#" + e.target.id).val() == 1)
        $("#" + e.target.id).val(0);
    else
        $("#" + e.target.id).val(1);
}

</script>


<div class="clearfix"></div>
<?php

$_publicLink = "/".$obj->getLinkFriendlyUrlEx();
if(isset($params['create_new']))
    $_publicLink = "#";

require_once "application/block/view/admin_view.php";




echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
print_r($params);
echo "</pre>";



if(isset($params['id'])){
$id = qqgetIdFromRand($params['id']);
if(!is_numeric($id)){
    loi("Not valid id?");
}
}

unset($obj->content);
unset($obj->summary1);
unset($obj->summary0);

echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
print_r($obj);
echo "</pre>";
?>


