<?php

$params = \Base\ClassRoute::getArrParams();
if(isset($params['create_new'])){
    $obj = new \Base\ModelDataFile();
    $obj->initEmptyObject();
}

if(isset($params['id'])){
    $idRand = $params['id'];
    $item_id = $id = qqgetIdFromRand($params['id']);
    if(!is_numeric($id)){
        loi("Not valid id?");
    }

    //bl("ID = $id");

    $obj = new \Base\ModelDataFile();
    if(!$obj->getOne($id)){
        bl("Không tồn tại id này? $idRand");
        return;
    }

    $obj->getLinkFriendlyAndInsertRoute();
}

?>

<style>
    .folder_select1{
        padding: 1px 2px; display: inline; border: 1px solid #ccc; border-radius: 5px; margin: 1px 2px;
        box-shadow: 1px 1px gray;
        cursor: pointer;
    }
</style>
<div style="padding: 10px">

<?php



\Base\ClassUploadSetting::$moduleUploadNow = 'image#';
\Base\ClassUploadSetting::$getStaticLinkAfterUpload = 1;
\Base\ClassUploadSetting::$module_info = "data_id_$obj->id";

require_once "application/block/upload_block.php";

require_once "application/block/js_editor_lad.php";

$module = \Base\ClassRoute::getCurrentModule();
$controller = \Base\ClassRoute::getCurrentController();
$action = \Base\ClassRoute::getCurrentAction();
$strToSaveSession = str_replace("-","_", $module.$controller.$action);



if($obj->delete_date){
    baoloi("Item bị xóa vào lúc: $obj->delete_date");
}
if($obj->delete_date){
    baoloi("Item bị xóa vào lúc: $obj->delete_date");
}

?>

<script>
    //    var urlBaseApiTree = "/a_p_i/member-image";// ?time=1516245801505&pid=folder_0
    //    var modulePublicTree = "image";
    //    var viewAsDefaultGridOrTable = 'grid'; //'table'

    function doneUploadFile(data) {
        //alert("Upload done!");

        console.log(" doneUploadFile data = " + JSON.stringify(data.payload));

        if(!ClassApi.checkReturnApi(data)){
            alert("Not valid return API after upload done? " + data);
            return;
        }
        console.log(" LINK IMG = " + data.payload[0].link_image_static);
        $("#img_zone").html($("#img_zone").html() + "<image style='width: 200px; margin: 3px; border: 1px solid darkslategray' src='" + data.payload[0].link_image_static + "'>");

    }

    function CopyFromDataId() {

        var dataId = $("#data_id_to_copy").val();
        console.log(" urlPost Save = " + urlPost);
        var data1 = {};
        var urlPost = '/a_p_i/member-data/copy-item/';
        data1['data_id_to_copy'] = dataId;
        showWaittingIcon();
        $.post(urlPost, data1, function(result){
            hideWaittingIcon();

            if(!ClassApi.checkReturnApi(result))
                return;
            if(result.payload == 0)
                showToastWarningBottom("Nothing update?");
            else {
                showToastInfoBottom("Done?");
                window.location.href = "<?php echo "/$module/$controller/view/id/" ?>" + result.payload;
            }

        });

    }

    function enableLink(id) {

        showWaittingIcon();
        var urlPost = '/a_p_i/member-data-link/change-status/id/' + id + '/field/status';
        $.post(urlPost, {}, function(result) {
            hideWaittingIcon();
            if (!ClassApi.checkReturnApi(result))
                return;
            showToastInfoBottom("Done?");
        });
    }

    function saveOrAddDataLink(saveId){
        var data1 = {};
        var urlPost = '/a_p_i/member-data-link/add/';
        if(saveId) {
            var urlPost = '/a_p_i/member-data-link/save/';
            var name_of_id_ = $("#name_of_id_" +  saveId).val();
            var link_of_id_ = $("#link_of_id_" +  saveId).val();
            var summary_of_id_ = $("#summary_of_id_" +  saveId).val();
            data1['id'] = saveId;
            data1['name'] = name_of_id_;
            data1['summary'] = summary_of_id_;
            data1['link'] = link_of_id_;
            data1['refer_remote'] = $("#refer_remote_save_" + saveId).val();
            data1['item_id'] = '<?php if(isset($item_id)) echo $item_id ?>';
        }
        else{
            var link_name_new = $("#link_name_new").val();
            var link_refer = $("#link_refer").val();
            var link_idcloud_new = $("#link_idcloud_new").val();
            var link_summary_new = $("#link_summary_new").val();
            data1['name'] = link_name_new;
            data1['refer_remote'] = link_refer;

            data1['summary'] = link_summary_new;
            data1['item_id'] = '<?php if(isset($item_id)) echo $item_id ?>';
        }

        console.log(" urlPost Add/Save datalink = " + urlPost);

        showWaittingIcon();
        $.post(urlPost, data1, function(result) {
            hideWaittingIcon();
            if (!ClassApi.checkReturnApi(result))
                return;
            if (result.payload == 0)
                showToastWarningBottom("No change?");
            else
                showToastInfoBottom("Done?");

            if(!saveId){
                //alert("Echo xxx");
                //$("#tbl_list_link tr:first").after('<tr><td style="color: red"><b>new link</b></td><td></td><td>' + link_name_new + '</td><td>' + link_summary_new + '</td><td>' + link_idcloud_new + '</td><td></td></tr>');
                //$("#tbl_list_link").closest('table').find('tr:last').prev().after('<tr><td style="color: red"><b>new link</b></td><td></td><td>' + link_name_new + '</td><td>' + link_summary_new + '</td><td>' + link_idcloud_new + '</td><td></td></tr>');
                $('<tr><td style="color: red"><b>new link</b></td><td></td><td>' + link_name_new + '</td><td>' + link_summary_new + '</td><td>' + link_idcloud_new + '</td><td></td></tr>').insertAfter("#tr_add_row_link");
            }

        });
    }


    setTimeout(function () {
        uploadObj.update({formData: {uploadModule: 'image_module_upload' }});
    }, 1000);
</script>


<div id="img_zone" style="border: 1px solid #ccc; padding: 2px">
    Image uploaded:
</div>

<?php
if(isset($params['create_new'])) {
    ?>
    <div>
        Copy From DataID <input type="text" id="data_id_to_copy" placeholder="Enter Data ID">
        <button onclick="CopyFromDataId()"> Copy</button> (Nếu nhiều ID cách nhau bởi dấu ,)
    </div>
    <?php
}
?>
<?php
if($action <> 'add'){


?>
<br>

<a title="select folder to browse" style="padding: 1px 5px; background-color: #eee ; box-shadow: 2px 2px ;
 border: 1px solid #ccc; border-radius: 5px" href="#" onclick="$('#myModalTreeSelectFolder').modal('show')"
   aria-hidden="false" class="">
    <i class="fa fa-folder"></i>
    Select Folder: <span id="selectingFolderPathToSave"><?php if($obj->id) echo $obj->getParentPathNames() ?></span>
    <i class="fa fa-caret-right" aria-hidden="true"></i>
</a>

<div ng-controller="TreeController" id="tree_in_edit_item">
    <?php require_once "application/block/tree_block_tplAddTo.php"?>

    <button id="add_item_to_folder<?php echo qqgetRandFromId($obj->id) ?>" title="Add To Multi Folder" style="margin-top: 5px; font-size: smaller; color: lightslategray; border-radius: 5px" role="button">
        <i class="fa fa-tree"></i>
        Add To Muti Folder
    </button>

    <?php
    //if(isAdmin_())
    {
    ?>
    <input type="text" id="add_folder_id" style="border-radius: 5px;" placeholder="Enter name...">

        <div id="folder_parent_list" style="margin-top: 5px">
            <?php
            $pAll = explode(",", $obj->parent_list);
            $pAll = array_unique($pAll);
            foreach ($pAll AS $pid){
                if(!$pid) continue;
                $fold = new \Base\ModelDataFolder($pid);
                if(!$fold->status)
                    continue;
                echo " <div id='check_multi_folder_$fold->id' title='Remove folder: $fold->name / $fold->id' class='folder_select1' style=''> <i class='fa fa-times' style='color: gray'></i> $fold->name </div> " ;
            }
            ?>
        </div>

<?php
    }
?>

</div>
    <?php
}
else
    echo "<h3>Thêm mục mới:</h3>";
?>

<div ng-app="ladApp" ng-controller="TreeController" id="tree_in_index_browse" style="">

    <script type="text/ng-template" id="tplTreeModalSelectFolder">
        <span style="" ng-click="toggleNodeLeft(menu.id, 0, 1)">
            <i style="margin: 0 5px" ng-show="menu.menus" class="fa fa-angle-down" aria-hidden="true"></i>
            <i style="margin: 0 5px" ng-show="!menu.menus" class="fa fa-caret-right" aria-hidden="true"></i>
        </span>
        <button style="border: 0px solid gray; background-color: transparent; overflow: hidden" id="folderToMove-{{menu.id}}"
                onclick="ClassTree.choiceFolderToMove(event)"
                onmouseup="ClassTree.hoverFolderToMove(event)"
                ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
                title="{{menu.name}}">
            <i style="color: #6B8E23;" id="folderToMove2-{{menu.id}}" class="fa fa-folder" aria-hidden="true"
               onclick="ClassTree.choiceFolderToMove(event)"
               onmouseup="ClassTree.hoverFolderToMove(event)"
               ng-dblclick="menu.type==0 ? toggleNodeLeft(menu.id, 0, 1) : ''"
               title="{{menu.name}}"></i>
            {{menu.name|limitTo:20}}{{menu.name.length > 20? "..." : ""}}
        </button>
        <span ng-click="selectFolderTree(menu.id)" style="background-color: gray; color: white; padding: 3px; margin: 1px"> select </span>

        <ul  ng-if="menu.menus">
            <li ng-repeat="menu in menu.menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
            </li>
        </ul>
    </script>


    <!-- Modal Popup Add to folder-->
    <div class="modal" id="myModalTreeSelectFolder" tabindex="-1" role="dialog" aria-labelledby="myModalTreeLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalTreeLabel">Chọn folder save Item</h4>
                </div>
                <div class="modal-body">

                    <ul>
<!--                        <a href="/{{_module}}/{{_controller}}/{{_action}}"> DUYỆT TẤT CẢ </a>-->

                        <li ng-repeat="menu in menus" ng-show="menu.type == 0" ng-include="'tplTreeModalSelectFolder'">
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">

                    <!--                    <input type="text" class="form-control" style="float: left; width: 150px; margin: 0px 5px;">-->
                    <!---->
                    <!--                    <button type="button" class="btn btn-success" style="float: left;">Tạo Folder</button>-->

                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

</div>


<script type="text/javascript">
    var urlBaseApiTree = '/a_p_i/member-data';
    tinymce.init({
        selector: '#content_textBoxEditable',
        plugins: [
            "anchor autolink codesample colorpicker contextmenu fullscreen help image imagetools",
            " paste code lists link media noneditable preview",
            " searchreplace table template textcolor visualblocks wordcount"
        ], //removed:  charmap insertdatetime print
        image_title: true,         entity_encoding : "raw",
        automatic_uploads: true,
        file_picker_types: 'image',
        paste_data_images: true,
        relative_urls : false,
        remove_script_host : true,
        document_base_url : "/",
        convert_urls : true,
        image_class_list: [
            {title: 'Responsive', value: 'img-responsive'}
        ],
        //toolbar: "sizeselect | bold italic | fontselect |  fontsizeselect | align | forecolor backcolor link image",
        toolbar:
            "insertfile a11ycheck undo redo paste | fontselect sizeselect fontsizeselect bold italic | forecolor backcolor | template codesample | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | ",
        textcolor_cols: "5",
        image_class_list: [
            {title: 'Responsive', value: 'img-responsive'}
        ],
        file_picker_callback: function(cb, value, meta) {
            var input = document.createElement('input');
            input.setAttribute('type', 'file');
            input.setAttribute('accept', 'image/*');
            input.onchange = function () {
                var file = this.files[0];
                var reader = new FileReader();

                reader.onload = function () {
                    var id = 'blobid' + (new Date()).getTime();
                    var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                    var base64 = reader.result.split(',')[1];
                    var blobInfo = blobCache.create(id, file, base64);
                    blobCache.add(blobInfo);
                    cb(blobInfo.blobUri(), {title: file.name});
                };
                reader.readAsDataURL(file);
            };
            input.click();
        }
    });


    setTimeout(function () {

        var scope = angular.element($("#tree_in_index_browse")).scope();
        if(!scope || typeof scope == 'undefined'){
            alert("Error: can not get scope?");
        }
        scope.selectFolderTree = function (id) {
            //alert("ID = " + id );
            // Simple GET request example:

            showWaittingIcon();

            var urlGet = "/a_p_i/member-data/get-item/id/" + id + "/filetype/0";
            $.get(urlGet, function(data, status){
                //alert("Data: " + data + "\nStatus: " + status);
                hideWaittingIcon();

                if(!ClassApi.checkReturnApi(data, urlGet))
                    return;

                ClassSettingApp.folderToSaveItem = id;

                console.log(" data = " + JSON.stringify(data));
                console.log(" data.payload._parent_path = " + data.payload._parent_path);

                $("#selectingFolderPathToSave").html(data.payload._parent_path);

                $('#myModalTreeSelectFolder').modal('hide');

                sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_id" ?> = id;
                sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?> = data.payload._parent_path;

            });
        }


        <?php
        //Neu la create new thì chọn sẵn folder đã chọn trước đó:
        if(isset($params['create_new'])){
        ?>
            if(sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?>){
                $("#selectingFolderPathToSave").html(sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_name" ?>);
                ClassSettingApp.folderToSaveItem = sessionStorage.<?php echo $strToSaveSession ."_selecting_folder_id" ?>;
            }
        <?php
        }
        ?>

    }, 1000);
    ////
</script>


<?php

    $arrEdit = $obj->getArrayEditable();
    $arrMeta = $obj->getMetaDataApi();

    echo "<br/><div style='float: left; max-width: 600px; padding : 10px'>";

    echo "<table class='glx03'>";
    foreach ($arrEdit as $field) {
        if(!in_array("$field", ['summary0','summary1','content','parent'])) {
            $val = $obj->$field;
            echo "<tr>";
            $fieldU = strtoupper($field);

            $fieldU = $obj->getMetaNameField("$field", null, $arrMeta);

            if(isset($params['create_new'])){
                if($field == 'price' || $field == 'status' || $field == 'price_original')
                    $val = 0;
                if($field == 'name'){
                    $val = 'new';
                }
            }

            if($obj->isStatusField($field)) {
                $padCheck = '';
                if($obj->$field)
                    $padCheck = 'checked';
                echo "<td>$fieldU: </td> <td style=''><input onclick='checkStatus_(event)' $padCheck type='checkbox'  id='edit_$field' value='$val'></td>";
            }
            else
                echo "<td>$fieldU: </td> <td><input style='width: 400px' class='form-control' id='edit_$field' value='$val' title='$val'></td>";

            echo "</tr>";
        }
        else{

        }
    }

    echo "</table>";

    echo "</div>";


?>
    <div class='div_img_data'>
        Img0 - Ảnh đại diện
        <br>
        <a target="_blank" href="<?php echo $obj->image0 ?>">
        <img class="img_data" src="<?php echo $obj->image0 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img1<br>
        <a target="_blank" href="<?php echo $obj->image1 ?>">
        <img class="img_data"   src="<?php echo $obj->image1 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img2<br>
        <a target="_blank" href="<?php echo $obj->image2 ?>">
        <img class="img_data"   src="<?php echo $obj->image2 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img3<br>
        <a target="_blank" href="<?php echo $obj->image3 ?>">
        <img class="img_data"   src="<?php echo $obj->image3 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img4<br>
        <a target="_blank" href="<?php echo $obj->image4 ?>">
        <img class="img_data"   src="<?php echo $obj->image4 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img5<br>
        <a target="_blank" href="<?php echo $obj->image5 ?>">
        <img class="img_data"   src="<?php echo $obj->image5 ?>">
        </a>
    </div>

    <div class='div_img_data'>
    Img6<br>
        <a target="_blank" href="<?php echo $obj->image6 ?>">
        <img class="img_data"   src="<?php echo $obj->image6 ?>">
        </a>
    </div>

    <?php
    if(ClassSetting::$siteId == 41) {
        ?>
        <style>
            #sortable { list-style-type: none; margin: 0; padding: 0; width: 100%; }
            #sortable li { margin: 3px 3px 3px 0; padding: 1px; float: left; text-align: center}
        </style>
        <script>
            $( function() {

                $( "#sortable" ).disableSelection();

                $( "#sortable" ).sortable({
                    update: function (event, ui) {

                        //alert("Stop ...");
                        console.log(" -------------- ");

                        var strIdImg = '';
                        $("[id^='cloud_id_img_']").each(function(){
                            console.log(" xx = " + this.id);
                            strIdImg += ',' + this.id;
                        });

                        console.log(" --------- strIdImg = " + strIdImg);
                        var urlPost = '/a_p_i/member-data/image-status?data_id=<?php echo $obj->id ?>&change_order_img=' + strIdImg;
                        console.log(" urlPostx = " + urlPost);
                        showWaittingIcon();
                        $.post(urlPost, {}, function(result) {
                            hideWaittingIcon();

                            if (!ClassApi.checkReturnApi(result))
                                return;
                            if (result.payload == 0)
                                showToastWarningBottom("Nothing update?");
                            else
                                showToastInfoBottom("Done?");
                        });
                    }
                });

                $("[id^='enable_img_cloud_']").click(function () {
                    console.log(" ID = " + this.id);
                    console.log(" Check = " + $(this).prop("checked"));
                    var urlPost = '/a_p_i/member-data/image-status?data_id=<?php echo $obj->id ?>&fileid='+ this.id + '&enable_img=' + $(this).prop("checked");
                    console.log(" urlPostx = " + urlPost);
                    showWaittingIcon();
                    $.post(urlPost, {}, function(result) {
                        hideWaittingIcon();

                        if (!ClassApi.checkReturnApi(result))
                            return;
                        if (result.payload == 0)
                            showToastWarningBottom("Nothing update?");
                        else
                            showToastInfoBottom("Done?");
                    });


                })

            } );


        </script>

    <div class='div_img_data'>
        <ul id="sortable">
            <?php

            $cfile = new \Base\ModelCloudFile();
            $mf = $cfile->getArrayWhereSql_(" module_info = 'data_id_$obj->id' ORDER BY order1 DESC, id ASC");
            if($mf)
            foreach ($mf as $cfile) {
                // echo "<br/>\n $cfile->name ";
                $linkImg = $cfile->makeDirectLink();

                $check = $st1 = "";
                if($cfile->order1 >= 0){
                    $check = "checked";
                }
                else
                    $st1 = "color: brown";

                echo "<li class=\"ui-state-default\" id=\"cloud_id_img_$cfile->id\"> 
<a href='$linkImg' target='_blank'> <img style='height: 150px' src='$linkImg'> </a>
<br>
<input type='checkbox' $check id='enable_img_cloud_$cfile->id'> <label for='enable_img_cloud_$cfile->id' style='$st1'>Show </label>
($cfile->order1) 
</li>";
            }
            ?>
        </ul>

    </div>
        <?php
    }
    ?>

<div class="clearfix"></div>
<b>Chú ý</b>: <u><b>IMG0</b></u> là ảnh đại diện,  cần vuông, cỡ khoảng 400x400 để hiển thị đẹp<br>
Có thể dùng Công cụ edit ảnh <a target="_blank" href="https://drive.google.com/open?id=0ByCxAWYxCj8LV3NIejdSN2tfN2s">SnagitEditor </a>
<br>

<span style="font-size: 16px; font-weight: bold; "> Tóm tắt: </span>
    <br>
<textarea style="border: 2px solid gray; height: 130px; width: 100%; max-width: 1000px"  rows="10" id="summary0" name="summary0"><?php echo $obj->summary0; ?></textarea>
<?php
if(ClassSetting::$siteId == 35) {
    ?>
    <br>
    Lịch chiếu:
    <br>
    <textarea style="border: 2px solid gray;  width: 100%; max-width: 1000px" rows="2" id="summary1"
              name="summary1"><?php echo $obj->summary1; ?></textarea>
    <?php
}
?>
    <div style="max-width: 1000px; margin: 0px; border: 2px solid gray; display: none">
    <div id="summary0xxxxx" contenteditable="true" class="textBoxEditable" style="height: 200px"><?php echo $obj->summary0; ?></div>
</div>
<br>

<!--<span style="font-size: 16px; font-weight: bold"> - Summary1: </span>-->
<!--<textarea cols="80" id="summary1" name="summary1">--><?php //echo $obj->summary1; ?><!--</textarea>-->

    <?php
    if(ClassSetting::$siteId == -1) {
        ?>
        <span style="font-size: 16px; font-weight: bold; "> Tóm tắt2: </span>
        <div style="max-width: 1000px; margin: 0px; border: 1px solid green">
            <textarea style="border: 2px solid gray; height: 130px; width: 100%; max-width: 1000px"  rows="10" id="summary1" name="summary0"><?php echo $obj->summary1; ?></textarea>
            <div id="summary1xxxxx" contenteditable="true" class="textBoxEditable" style="display: none; height: 100px"><?php echo $obj->summary1; ?></div>
        </div>
        <?php
    }
    ?>

<!--<span style="font-size: 16px; font-weight: bold"> - Summary2: </span>-->

<!--<textarea cols="80" id="summary2" name="summary2">--><?php //echo $obj->summary2; ?><!--</textarea>-->


    <?php
    if(ClassSetting::$siteId != 35)
    {
        ?>

        <span style="font-size: 16px; font-weight: bold; color: "> Nội dung: </span>
        <!----- CONTENT ----->
        <!--<textarea cols="80" id="content" name="content"></textarea>-->
        <form name="compForm" onsubmit="return false;">
            <input type="hidden" name="myDoc">

            <div style="max-width: 1000px; margin: 0px; border: 2px solid gray">
                <div id="content_textBoxEditable"
                     style="min-height: 300px; max-height: 1000px"><?php echo $obj->content; ?></div>
            </div>

            <textarea id="textAreaContent"
                      style="display: none; width: 100%; min-height: 400px; border: 3px solid green; background-color: lavender"><?php echo $obj->content; ?></textarea>
        </form>
        <?php
    }
    ?>
<?php
require_once "application/block/upload_image_clipboard.php";
require_once "application/block/waitting_icon.php";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//LINK DATA/////////////////////////////////////////////////////////////////////////////////////////////////////
if (isset($item_id)) {
    ?>
    <div style="margin-top: 10px; overflow: auto">

        <span style="font-size: 16px; font-weight: bold; color: "> DataLinkList1</span>

        <?php
            if(\clsValidate::isURL($obj->refer)){

                echo " Refer link: <b> <a target='_blank' href='$obj->refer'>$obj->refer</a></b>";
                $cr = new \Base\ModelDataCrawle();
                if($cr->getOneWhere_(" refer = '$obj->refer'")){
                    echo " | <a href=''>Crawle ID = $cr->id  </a>, LastStart/Done: $cr->last_start / ";
                    if($cr->last_start < $cr->last_done )
                        echo "$cr->last_done";
                }
            }

        $arrName = [];
        ?>

        <table id="tbl_list_link" class="glx01 table table-bordered pagin-table" style="">
            <tr>
                <th>STT</th>
                <th>Thứ <br> tự </th>
                <th>Tên link <br>(Option)</th>
                <th>Thuyết minh?</th>
                <th>Refer link</th>
                <th>CreateTime <br>/ Modified</th>
                <th>Summary</th>
                <th>IDCloud</th>
<!--                <th>FileNamex</th>-->
                <th>Enable</th>
                <th></th>
            </tr>
            <tbody id="sort_me">
            <?php
            if (isset($item_id)) {
                echo "<tr id='tr_add_row_link' style='background-color: #ccccff'>";
                echo "<td> </td>";
                echo "<td></td>";
                echo "<td><input style='width: 100px' placeholder='Enter new name of link' id='link_name_new' type='text' value=''></td>";


                echo "<td></td>";

                echo "<td><input placeholder='Refer link' id='link_refer' type='text' value=''></td>";
                echo "<td></td>";
                echo "<td><textarea style='max-height: 100px; width: 200px' placeholder='Enter summary' id='link_summary_new' type='text' ></textarea></td>";

                echo "<td><input placeholder='Enter id cloud file' id='link_idcloud_new' type='text' value=''></td>";

                echo "<td></td>";

                echo "<td> <button  id='add_new_link' class='btn btn-info' onclick='saveOrAddDataLink()'>
<i class='fa fa-plus'></i> 
ADD LINK 
</button> </td>";
                echo "</tr>";

                $objLink = new \Base\ModelDataLink();
                if ($arr = $objLink->getArrayWhereSql_(" item_id = $item_id order by orders DESC,  id DESC")) {
                    $c = 0;
                    foreach ($arr AS $link) {

                        $c++;

                        if ($link instanceof \Base\ModelDataLink);

                        $padNotHaveCloud = "";
                        if(!$link->link){
                            $padNotHaveCloud = " style='color: red;'";
                        }

                        $padPlay = '';
                        if(ClassSetting::$siteId == 35)
                        if($link->link || strstr($link->summary,'/ok.ru/video/')){
                            $l1 = $obj->getLinkFriendlyUrl2('phim');
                            $padPlay = "<a title='Xem phim Tập: $link->name' target='_blank' href='$l1?tap_id=".qqgetRandFromId($link->id)."'> <i class='fa fa-2x fa-play-circle-o'></i> </a>";
                        }
                        else
                            $padPlay = "<i class='fa fa-2x fa-question-circle-o'></i>";

                        echo "<tr $padNotHaveCloud id='tr_id_link_$link->id'>";
                        echo "<td> <a href='/admin/data-link/view/id/$link->id' target='_blank'> $c <br> <span style='font-size: smaller'>$link->id </span> </a></td>";
                        echo "<td align='center'>".@$link->orders." </td>";



                        $padTrungTen = '';
                        if($link->status == 1)
                        if(!in_array($link->name, $arrName)){
                            $arrName[] = $link->name;
                        }
                        else{
                            $padTrungTen = " <div style='color: red'> Trùng tên rồi Bro!</div>";
                        }

                        echo "<td><input style='font-size: x-small' id='name_of_id_$link->id' type='text' value='$link->name'> $padPlay $padTrungTen <br> <span style='font-size: x-small'>$link->name</span></td>";

                        if($link->type)
                            echo "<td align='center'> Thuyết minh!</td>";
                        else
                            echo "<td align='center'>  </td>";

                        $paddownload = '';

                        $filepathX = "/share/film_".DOMAIN_MAIN.".$link->id.mp4";
                        $filepathX = $filepathX0 = "/mnt/sdb1/film_".DOMAIN_MAIN.".$link->id";
                        $filepathX1 = "/mnt/sdb1/film_".DOMAIN_MAIN.".$link->id.mp4";

                        if(!$link->link){
                            if(file_exists($filepathX1)){
                                $filepathX = $filepathX1;
                            }

                            if(file_exists($filepathX)){
                                if(filesize($filepathX) == 0)
                                    $paddownload = "<br>Download error, size = 0";
                                else {
                                    $paddownload = ByteSize(filesize($filepathX));
                                    if(filemtime($filepathX) < time() - 10)
                                        $paddownload = "<br>Download Done, watting for save to cloud: $paddownload ...";
                                    else{
                                        $paddownload = "<br>Downloading: $paddownload ...";
                                    }
                                }
                            }
                            if(file_exists($filepathX0)){
                                $paddownload = ByteSize(filesize($filepathX0));
                                $paddownload = "<br>Downloading: $paddownload ...";
                            }
                        }

                        $padDlInfoLast = "";
                        if(!$link->link)
                            $padDlInfoLast = "<br><span style='font-size: x-small; color: blue;'> Last Log: ... ". substr($link->log, -100)."...</span>";

                        $padByUser = '';
                        if(!$link->refer_remote){
                            $padByUser = "<i> UploadedBy: " . \Base\ModelUserCms::getUserInfoEx($link->userid, 'email') ."</i> <br/>
<input placeholder='Refer link' id='refer_remote_save_$link->id' type='text' value=''>";

                        }

                        if($link->refer_remote)
                            echo "<td><a target='_blank' href='$link->refer_remote' title='$link->refer_remote'> ".\Base\ClassString::substr_fit_word(basename($link->refer_remote),0,80)." </a> $paddownload $padDlInfoLast <br/>  <span style='color: gray; font-size: smaller'>$link->extra1 <span> </td>";
                        else {
                            echo "<td> $padDlInfoLast $padByUser </td>";
                        }

                        echo "<td style='font-size: x-small'>$link->createdAt <br> $link->modifiedAt </td>";

                        echo "<td><textarea style='max-height: 100px; width: 200px' id='summary_of_id_$link->id' type='text' >$link->summary</textarea> </td>";

                        $padSize = "";
                        $id0 = $link->link;
                        if(strlen($link->link) > 10){
                            $id0 = d_f_h_1b($link->link);


                        }
                        $objFile = new \Base\ModelCloudFile();

                        if($id0)
                        if($objFile->getOne($id0)){
                                $padSize = "<br>".ByteSize($objFile->size);
//                            $pad = \Base\ClassString::substr_fit_word($objFile->name, 0, 100)."..." ;
//                            $pad = "<a target='_blank' href='/admin/cloud-file/view/id/".@$objFile->id."'>".$pad."</a>";
//                            //echo "$pad";
//                            echo "<td title='".@$objFile->name."'> $pad </td>";
                        }else {
//                            $pad = "Not found cloud file? \n ($link->link / $link->refer_remote / $link->name )";
//                            echo "<td title='".@$objFile->name."'> <textarea  rows='2'>$pad</textarea></td>";
                        }

                         //<br> Size = ".ByteSize($);
                        $padLinkCl = "x";
                        if(!\clsValidate::isURL($link->link)){
                            if(strlen($link->link) < 10){
                                if(is_numeric($link->link)){
                                    $padLinkCl = "<a target='_blank' href='/admin/cloud-file/view/page/1/name/$link->link'> LINK </a> $padSize";
                                }
                            }
                            else{
                                $x = dfh1b($link->link);
                                $padLinkCl = "<a  target='_blank' href='/admin/cloud-file/view/page/1/name/$x'> LINK </a> $padSize";
                            }
                        }
                        else{
                            $padLinkCl = "<a href='$link->link' target='_blank'>[L]</a>";
                        }

                        echo "<td><input id='link_of_id_$link->id' type='text' value='$link->link'> $padLinkCl </td>";



                        $pad = '';
                        if($link->status)
                            $pad = 'checked';

                        echo "<td align='center'><input $pad type='checkbox' id='link_enable_$link->id' onclick='enableLink($link->id)'> </td>";


                        echo "<td><button  class='btn btn-warning' onclick='saveOrAddDataLink($link->id)'>SAVE</button>  </td>";
                        echo "</tr>";
                    }
                    $c++;
                }


            }
            ?>
            </tbody>
        </table>
    </div>
    <?php
}    ?>

<script>

    //$('tbody').sortable({
    $('#sort_me').sortable({
        stop: function (event, ui) {

            console.log("sortable Stop...");

            var strOrderLink = '';
            $("#tbl_list_link").find("tr").each(function(){

                if(this.id.indexOf('tr_id_link_') >=0){
                    var idx = this.id;
                    var idxOK = idx.replace('tr_id_link_' , '');
                    console.log("OK..." + idxOK);
                    strOrderLink += idxOK + ",";
                }
//                IDs.push(this.id);
            });

            if(strOrderLink.length == 0){
                return;
            }

            console.log(" str = " + strOrderLink);
            var urlPost = '/a_p_i/member-data-link/change-order/str_id_order/' + strOrderLink;

            console.log(" urlPostx = " + urlPost);

            showWaittingIcon();
            $.post(urlPost, {}, function(result) {
                hideWaittingIcon();

                if (!ClassApi.checkReturnApi(result))
                    return;
                if (result.payload == 0)
                     showToastWarningBottom("Nothing update?");
                else
                    showToastInfoBottom("Done?");
            });



            }
    });


    $(document).ready(function(){

        $("#add_new_link").click(function () {

        });
    });

    function deleteItemData(){


        <?php
        if($obj->delete_date){
        ?>
            var urlPost = '/a_p_i/member-data/un-delete/?' + "&id=" + '<?php echo $obj->id ?>';
        <?php
        }
        else{
        ?>
            var r = confirm("Bạn sẽ xóa mục này? (Đánh dấu xóa, có thể khôi phục)");
            if (r == false) {
                return;
            }
        var urlPost = '/a_p_i/member-data/delete/?' + "&id=" + '<?php echo $obj->id ?>';
        <?php
        }
        ?>

        console.log(" urlPost Save = " + urlPost);

        showWaittingIcon();

        $.post(urlPost, {}, function(result){
            hideWaittingIcon();

            if(!ClassApi.checkReturnApi(result))
                return;
            if(result.payload == 0)
                showToastWarningBottom("Nothing update?");
            else {
                alert("Delete/UnDelete Done?");
                location.href = '';
            }
        });
    }

    function saveData() {
//        alert("Save dataa");

        var data1 = {};
        <?php
            foreach ($arrEdit as $field) {
        ?>
                data1['<?php echo $field?>'] = $("#edit_" + '<?php echo $field?>').val();
        <?php
            }
        ?>

        //var summary0 = CKEDITOR.instances['summary0'].getData();
        //var summary0 = $("#edit_summary0").val();
        //var summary1 = CKEDITOR.instances['summary1'].getData();
        //var summary2 = CKEDITOR.instances['summary2'].getData();
        //var content = CKEDITOR.instances['content_textBoxEditable'].getData();


        ////////
        //val() is ok for \n, but html() or text() will ignore \n
        var summary0 = $("#summary0").val();
        //var summary0 = $("#edit_summary0").val();
        var summary1 = $("#summary1").val();
        var summary2 = $("#summary2").html();

        //alert("Sum0 = " + summary0);

//        var content = $("#content_textBoxEditable").html();

        if (document.getElementById('content_textBoxEditable')) {
            var content = tinymce.get('content_textBoxEditable').getContent();

        } else {
            var content = '';
        }

        var sourceText = $("#sourceText").html();
        if(sourceText) {
            content = sourceText;
            console.log(" OK sourceText : " + content.substring(1,100));
        }
        else {
            console.log(" NOT sourceText : " + content.substring(1,100));
        }

        data1['summary0'] = summary0;
        data1['summary1'] = summary1;
        data1['content'] = content;

        if(ClassSettingApp.folderToSaveItem)
            data1['parent'] = ClassSettingApp.folderToSaveItem;

        console.log(" DAA1 = " + JSON.stringify(data1));

        <?php
            if(isset($params['create_new'])){
        ?>
            var urlPost = '/a_p_i/member-data/add/';
        <?php
        }
        else{
        ?>
            var urlPost = '/a_p_i/member-data/save/?' + "&id=" + '<?php echo $obj->id ?>';
        <?php
        }
        ?>

        console.log(" urlPost Save = " + urlPost);

        showWaittingIcon();
        $.post(urlPost, data1, function(result){
            hideWaittingIcon();

            if(!ClassApi.checkReturnApi(result))
                return;
            if(result.payload == 0)
                showToastWarningBottom("Nothing update?");
            else
                showToastInfoBottom("Done?");

            <?php
            if(isset($params['create_new'])){
            ?>
                window.location.href = "<?php echo "/$module/$controller/view/id/" ?>" + result.payload;
            <?php
            }
            ?>
    });
}

function checkStatus_(e) {
    //alert("Check status..." + e.target.id);
    if($("#" + e.target.id).val() == 1)
        $("#" + e.target.id).val(0);
    else
        $("#" + e.target.id).val(1);
}


$("[id^='add_item_to_folder']").click(function () {
    var iditem = this.id.replace('add_item_to_folder', '');
    ClassTree.addToMultiFolder2(iditem);
    //$("[id^='td_row_music']").css("color", "white");
    //$("#td_row_music" + pos).css("color", "orange");
});

</script>

<div class="clearfix"></div>
<?php

if(ClassSetting::$siteId == 35)
    $_publicLink = "/phim/".$obj->getLinkWithId();
elseif(ClassSetting::$siteId == 10)
    $_publicLink = "/".$obj->getLinkFriendlyUrlEx();
else{
    $_publicLink = $obj->getLinkFriendlyUrl2();
}

$_publicLink = $obj->getLinkFriendlyUrlSimple();

if(isset($params['create_new']))
    $_publicLink = "#";

require_once "application/block/view/admin_view.php";


if(ClassSetting::$siteId == 45){


    if(isset($params['addMultiLinkFs'])){

        $linkfsStr = $params['addMultiLinkFs'];

        $mlink = explode("\n", $linkfsStr);

//        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//        print_r($mlink);
//        echo "</pre>";

        foreach ($mlink AS $link1){
            $link1 = trim($link1);
            if(!$link1 || (!strstr($link1, "fshare.vn/f") && !strstr($link1, "subscene")))
                continue;

            $link1 = FshareClass::getFixLinkFshareFormat($link1);
            echo "<br/>\n$link1";

            $olink = new \Base\ModelDataLink();

            if(!$olink->getOneWhere_("item_id = $item_id AND refer_remote = '$link1'")){
                $olink->refer_remote = $link1;
                $olink->userid = getCurrentUserId();
                $olink->item_id = $item_id;
                $olink->addLog("Add multi FS file!");
                $olink->insertDbMe();
                echo "<br/>\n Insert done!";
            }
            else{
                echo "<br/>\nDa co file nay: $link1";
            }
        }

    }
    ?>


    <form action="" method="post">
    <textarea name="addMultiLinkFs" style="width: 100%; height: 100px"></textarea>  <button onclick="addMultiLinkFS()"> addMultiLinkFS </button>
    </form>


    <?php
}



echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
print_r($params);
echo "</pre>";



if(isset($params['id'])){
$id = qqgetIdFromRand($params['id']);
if(!is_numeric($id)){
    loi("Not valid id?");
}
}

$obj->content = substr(strip_tags($obj->content), 0 , 50)."...";
//$obj->summary1 = substr(strip_tags($obj->summary1), 0 , 50)."...";
//$obj->summary0 = substr(strip_tags($obj->summary0), 0 , 50)."...";
//$obj->summary2 = substr(strip_tags($obj->summary2), 0 , 50)."...";




if(isAdmin_()) {
    echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
    print_r($obj);
    echo "</pre>";
}
?>

</div>

<script>
    $( "#add_folder_id" ).autocomplete({
        source: "https://<?php echo DOMAIN_MAIN  ?>/tool/phim/addMultiFolderPhim.php",
        minLength: 2,
        select: function( event, ui ) {
            //alert( "Selected: " + ui.item.value + " aka " + ui.item.id );
            <?php
            echo "var itemId = $obj->id;";
            ?>
            ClassTree.checkAddToMultiFolder(itemId , ui.item.id, 1);

            //$("#search_string1").val(ui.item.value);
            //$("#form_search_pc").submit();
            var nameUp = ui.item.value.charAt(0).toUpperCase() + ui.item.value.slice(1);
            $("#folder_parent_list").append("<div class='folder_select1' style='background-color: darkred; color: white' id='check_multi_folder_"+ui.item.id+"'> [v] " + nameUp + " </div>");
        }
    });

    $("[id^='check_multi_folder_']").click(function () {
        var folderId = this.id.replace('check_multi_folder_', '');

        <?php
        echo "var itemId = $obj->id;";
        ?>
        if(ClassTree.checkAddToMultiFolder(itemId , folderId, 0) == 1){
            $("#check_multi_folder_" + folderId).remove();
        }
        //$("[id^='td_row_music']").css("color", "white");
        //$("#td_row_music" + pos).css("color", "orange");
    });


</script>
