<section class="content">



    <?php

    ?>

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-sm-2"></label>
            <div class="col-sm-8">
                <h4>DATA SETTING</h4>
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Hot folder ID:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="option_folder_id0" placeholder="Enter HOT FOLDER ID (A...)">
            </div>
        </div>

<!--        <div class="form-group">-->
<!--            <label class="control-label col-sm-2" for="pwd">Password:</label>-->
<!--            <div class="col-sm-8">-->
<!--                <input type="password" class="form-control" id="pwd" placeholder="Enter password">-->
<!--            </div>-->
<!--        </div>-->


<!--        <div class="form-group">-->
<!--            <div class="col-sm-offset-2 col-sm-10">-->
<!--                <div class="checkbox">-->
<!--                    <label><input type="checkbox"> Remember me</label>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" onclick="saveData()">SAVE</button>
            </div>
        </div>
    </div>

</section>

<script>

    function saveData() {
//        alert("Save dataa");

        var data1 = {};

        data1['option_folder_id0'] = $("#option_folder_id0").val();

        var urlPost = '/a_p_i/site-mng/data-setting/';

        showWaittingIcon();
        $.post(urlPost, data1, function(result){
            hideWaittingIcon();

            if(!ClassApi.checkReturnApi(result))
                return;
            if(result.payload == 0)
                showToastWarningBottom("Nothing update?");
            else
                showToastInfoBottom("Done?");
        });
    }

</script>


