<?php

if(getCurrentGid() == 3){
    echo " EMPTY CONTENT ! ";
    return;
}

?>

<link rel="stylesheet" href="/train/ssh-web/PHP-SSH2-Web-Client/node_modules/xterm/dist/xterm.css" />
<script src="/train/ssh-web/PHP-SSH2-Web-Client/node_modules/xterm/dist/xterm.js"></script>
<script src="/train/ssh-web/PHP-SSH2-Web-Client/node_modules/xterm/dist/addons/attach/attach.js"></script>
<script src="/train/ssh-web/PHP-SSH2-Web-Client/node_modules/xterm/dist/addons/fit/fit.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->



<!-- Content Header (Page header) -->
<style>
    .info2{
        width: 100%; height: 200px;
    }
    .info1{
        width: 100%; height: 200px;
    }
    .cls1{
        padding: 20px;
        border: 1px solid #eee;
        border-radius: 10px;
        margin: 10px;
        background: snow;
    }

    .cls1 a{
        font-weight: bold;
    }

</style>
<section class="content-header">
    <h1>
        <?php
        echo nowyh();
        ?>
        <small>

        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <a target="_blank" href="/admin/hosting/list-vps2">
                <div class="info-box">
                    <span class="info-box-icon bg-aqua"><i class="fa fa-server"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Admin</span>
                        <span class="info-box-number">List VPS</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
            </a>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <a target="_blank" href="/admin/hosting/list-ip">
                <div class="info-box">
                    <span class="info-box-icon bg-green"><i class="fa fa-address-book"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Admin</span>
                        <span class="info-box-number">List IP Address</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
            </a>
        </div>

        <?php
        if(isAdmin_()){
        ?>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <a target="_blank" href="/tool/_hosting_api/total_vm.php">
                <div class="info-box">
                    <span class="info-box-icon bg-yellow"><i class="fa fa-money"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Admin</span>
                        <span class="info-box-number">Billing</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
            </a>
        </div>

        <?php
        }
        ?>


    </div>

    <div class="row" style="padding: 0px 15px">
        <?php
        require "ssh.php";
        ?>
    </div>

</section>
<!-- /.content -->
<script>
    $(document).ready(function(){
        var $textarea = $('.info1');
        $textarea.scrollTop($textarea[0].scrollHeight);
    });
</script>
