<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
        <small>Cloud FileView1</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Cloud File</li>
    </ol>
</section>

<!-- Main content -->
<section class="content" ng-controller="cloud_file_index">

    <?php

    $params = \Base\ClassRoute::getArrParams();
    echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
    print_r($params);
    echo "</pre>";
    if(isset($params['name'])){
        $id = $params['name'];
    }
    if(isset($params['id'])){
        $id = $params['id'];
    }
    if(isset($id))
    if($id = qqgetIdFromRand($id)) {
        $obj = new \Base\ModelCloudFile($id);
        $link = new \Base\ModelDataLink();

        if($link->getOneWhere_("refer_remote = '$obj->refer_url'")){

            echo "<br/> <a href='/admin/data-link/view/id/$link->id' target='_blank'> Data Link</a>";

            echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
            print_r($link);
            echo "</pre>";

        }
        else{
            bl("Not found phim link");
        }

        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
        print_r($obj);
        echo "</pre>";
    }


    ?>

</section>
<!-- /.content -->
<!-- Main content -->