<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Data Setting
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Index</li>
    </ol>
</section>

<!-- Main content -->
<section class="content" ng-controller="data_setting_view">

    <?php
    require_once "application/block/default_index_one_item.php";
    ?>

</section>
<!-- /.content -->
<!-- Main content -->