<!-- Content Header (Page header) -->
<style>
    .info1{
        width: 100%; height: 200px;
    }
</style>
<section class="content-header">
    <h1>
        <?php
        echo nowyh();
        ?>
        <small>
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">
                <a href="/tool/_site/baogame/tmp-xoa-trung-bai.php" target="_blank">Kiểm tra trùng</a>
            </h3>
        </div><!-- /.box-header -->
    </div>
    
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">CRAWLE LOG : </h3>
        </div><!-- /.box-header -->
        <?php
        $logFile = "/var/glx/weblog/baogame/crawler.log";
        if(!file_exists(dirname($logFile)))
            mkdir(dirname($logFile));
        if(!file_exists($logFile))
            outputT($logFile, "START LOG");
        $lastIndexInfo = CFile::getNByteLast($logFile , 10000);

        $str = shell_exec("ps -ef |grep baogame/");

        $m1 = explode("\n", $str);
        $prList = '';
        $c1 = 0;
        foreach ($m1 AS $l1){

            if(strstr($l1, "/var/www/galaxycloud/tool/_site/")){
                $c1++;
                $proc = explode("/var/www/galaxycloud/tool/_site/baogame/", $l1)[1];
                //echo "<br/>\n $proc";
                $prList.="\n ($c1) ". $proc." | ";
            }
        }

        //$lastIndexInfo.= "\n--Running:--\n".$prList;

        echo "<textarea class='info1'>$lastIndexInfo";
        echo "</textarea>";

        echo "<br/>\n RUNNING $c1: $prList ";
        if($c1 < 6){

            echo "<br/>\n <span style='color: red'> *** Thiếu ".(6-$c1)." tiến trình kéo???</span>";
        }
        ?>
    </div>
</section>
<!-- /.content -->

<script>
    $(document).ready(function(){
        var $textarea = $('.info1');
        $textarea.scrollTop($textarea[0].scrollHeight);
    });

    function saveIPList() {
        var text1 = $('#ipListBlock').val();
        //alert("Text = " + text1);
        var data = {};
        data['ip_list'] = text1;
        var urlPost = "/a_p_i/admin/save-ip-block-list";
        $.post(urlPost, data, function(result){
            if(result.indexOf('no_change_ip_list') != -1){
                showToastWarningTop("NO THING CHANGE!");
                return;
            }
            if(result.indexOf('done_change_ip_list') != -1){
                showToastInfoTop("DONE!");
            }
            else{
                console.log(" Error1 = " + JSON.stringify(result));
                alert("Error: " + result);
            }
        });
    }
</script>
