<?php
/**
 * Created by PhpStorm.
 * User: lad
 * Date: 14/12/2017
 * Time: 2:58 PM
 */


namespace A_p_iModule;

use Base\ClassControllerApiHasIndex;
use Base\ClassControllerApiHasTree;
use Base\ClassDBConnect;
use Base\ClassUserProfile;
use Base\ModelCloudUser;
use Base\ModelDataFile;
use Base\ModelDataFolder;
use Base\ModelImageCmsFile;
use Base\ModelImageCmsFolder;
use Base\ModelUserCms;
use Base\clsValidate;
use Base\ModelCloudFile;
use Base\CReturnError;
use Base\ClassRoute;
use Base\ClassString;
use Base\ClassController;
use Base\ModelCloudFolder;
//use Base\ModelCloudFile;

use Base\ModelTree;

class AdminCloudFileController extends ClassControllerApiHasIndex
{

    function __construct(){
        parent::__construct();
        $this->isAdmin = true;
    }

    function indexAction($paramInput = null)
    {
        return parent::indexAction($paramInput); // TODO: Change the autogenerated stub
    }

    function getClassModelFolder(){
        return get_class(new ModelCloudFolder());
    }

    function getClassModelItem(){
        return get_class(new ModelCloudFile());
    }


}