<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        EDIT user
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">User list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content" ng-controller="cms_user_index">

    <?php

    $params = \Base\ClassRoute::getArrParams();

    if(isset($params['id'])){

        $id = $params['id'];

        if(is_numeric($id)) {
            $obj = new \Base\ModelUserCms($id);

            echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
            print_r($obj);
            echo "</pre>";
        }

    }

    ?>


</section>
<!-- /.content -->
<!-- Main content -->