<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
        <small>Danh sách người dùng</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">User list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
<?php
use Base\ModelBase;
use Base\ClassRoute;
//die();
?>
<link rel="stylesheet" href="<?php echo ClassRoute::getTemplateUri() ?>/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="box" ng-cloak ng-controller="cms_user_index" id="div_cms_user_index" style="display: yes">
    <!-- /.box-header -->
    <div class="box-body">
        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
                <div class="col-sm-6">
                    <div class="dataTables_length" id="example1_length">
                        <label>
                            Show
                            <select name="example1_length" aria-controls="example1" class="form-control input-sm">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                            entries
                        </label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div id="example1_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control input-sm" placeholder="" aria-controls="example1"></label></div>
                </div>
            </div>
            <div class="row">


                <p style="position:fixed;left: 50%;z-index: 10000" ng-hide="dataLoaded">
                    <i class="fa fa-spinner fa-spin fa-2x"></i>
                </p>
                </center>                
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing {{fromItem}} to {{toItem}} of {{totalRow}} entries</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                        <ul class="pagination">
                            <!--                            <li class="paginate_button previous disabled" id="example1_previous"><a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a></li>-->


                            <!--                                <li class="paginate_button active"><a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0">1</a></li>-->
                            <li  ng-repeat="page in arrPage" class="{{page.class}} ">
                                <!--                                <a ng-click="getUserList(page.page_number)"  href="{{page.link}}">{{page.name}}</a>-->
                                <a href="#" ng-click="getUserList(page.page_number)" >{{page.name}}</a>
                                <!--                                <a href="{{page.link}}" aria-controls="example1" data-dt-idx="6" tabindex="0">{{page.name}}</a>-->
                            </li>


                            <!--                            <li class="paginate_button next" id="example1_next"><a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a></li>-->
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="">ID</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">Username</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 322px;">Email</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 257px;">...</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 190px;">...</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="user in userArr">
                                <td>{{user.id}}</td>
                                <td>{{user.username}}</td>
                                <td>{{user.email}}</td>
                                <td></td>
                                <td></td>

                            </tr>

                        </tbody>
                        <tfoot>
                            <tr>
                                <th rowspan="1" colspan="1">Rendering engine</th>
                                <th rowspan="1" colspan="1">Browser</th>
                                <th rowspan="1" colspan="1">Platform(s)</th>
                                <th rowspan="1" colspan="1">Engine version</th>
                                <th rowspan="1" colspan="1">CSS grade</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing {{fromItem}} to {{toItem}} of {{totalRow}} entries</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">

                        <ul class="pagination">
                            <!--                            <li class="paginate_button previous disabled" id="example1_previous"><a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a></li>-->


                            <!--                                <li class="paginate_button active"><a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0">1</a></li>-->
                            <li  ng-repeat="page in arrPage" class="{{page.class}} ">
                                <!--                                <a ng-click="getUserList(page.page_number)"  href="{{page.link}}">{{page.name}}</a>-->
                                <a href="#" ng-click="getUserList(page.page_number)" >{{page.name}}</a>
                                <!--                                <a href="{{page.link}}" aria-controls="example1" data-dt-idx="6" tabindex="0">{{page.name}}</a>-->
                            </li>


                            <!--                            <li class="paginate_button next" id="example1_next"><a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a></li>-->
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
</div>
<!--<div class="center" style="display: none" id="DivListUserReverse">-->
<!--    <br/>-->
<!--    Không có quyền truy cập!-->
<!--    <br/>-->
<!--</div>-->
</section>
<!-- /.content -->
