<?php
//header('Access-Control-Allow-Origin: *');
?>
<link rel="stylesheet" type="text/css" href="/library_ex/vmlib/css/vmks-all.css"/>
<script type="text/javascript" src="/library_ex/vmlib/vmks.min.js"></script>
<script type="text/javascript" src="/library_ex/vmlib/vm-ctrl.js?v=<?php echo filemtime('/var/www/galaxycloud/library_ex/vmlib/vm-ctrl.js'); ?>"></script>

<script>
    window.console = window.console || function (t) {
    };
    if (document.location.search.match(/type=embed/gi))
        window.parent.postMessage("resize", "*");
</script>

<style>
    /* horizontal panel*/
    .panel-container {
        display: flex;
        flex-direction: row;
        border: 1px solid silver;
        overflow: hidden;
        /* avoid browser level touch actions */
        xtouch-action: none;
    }

    .panel-left {
        flex: 0 0 auto;
        /* only manually resize */
        padding: 10px;
        width: 200px;
        min-height: 200px;
        min-width: 150px;
        white-space: nowrap;
    }

    .splitter {
        flex: 0 0 auto;
        width: 2px;
        background: url('/public/images/vsizegrip.png') center center no-repeat #ccc;
        min-height: 200px;
        cursor: col-resize;
    }

    .panel-right {
        flex: 1 1 auto;
        /* resizable */
        width: 100%;
        min-height: 200px;
        min-width: 200px;
    }
</style>


<style>
    /* width */
    ::-webkit-scrollbar {
        width: 5px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
        background: #f1f1f1;
    }

    /* Handle */
    ::-webkit-scrollbar-thumb {
        background: #aaa;
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
        background: #bbb;
    }
</style>


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        ManagerServerVps
        <small>Index</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

    </ol>
</section>

<!-- Main content -->
<section class="content">

    <?php
    $params = \Base\ClassRoute::getArrParams();
    if (!isAdminGroup_()) {
        bl(" NOT ADMIN!");
        goto _END;
    }

    $file = "/var/ufile_cms2017LAD/vsphere-automation-sdk-java/test1";

    $un = getUserVcFromFile($file)[0];
    $pw = getUserVcFromFile($file)[1];

    $domain = "vc.glx";

    //ClassVMwareTool::loginVCCache($domain, $un, $pw);
    ClassVMwareTool::loginVC($domain, $un, $pw);

    $mhost = ClassVMwareTool::getHostList();

    $cc = 0;
    $vmList = [];
    foreach ($mhost AS $objh) {
        $cc++;
        //$vmList1 = ClassVMwareTool::getVMListPowerOn('name', "?filter.hosts.1=$objh->host");
        $vmList1 = ClassVMwareTool::getVMList(null, 'name', "?filter.hosts.1=$objh->host");
        $vmList = array_merge($vmList, $vmList1);
    }


    foreach ($vmList AS $vm) {
        if ($vm instanceof ClassVMinfo) ;
        foreach ($mhost AS $host) {
            if ($vm->hostId == $host->host) {
                $vm->hostName = $host->name;
            }
        }
    }

    //    echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
    //    print_r($vmList);
    //    echo "</pre>";

    //$vmList = ClassVMwareTool::getVMListPowerOn('name', "?filter.hosts.1=host-77");
    //$vmList2 = ClassVMwareTool::getVMListPowerOn('name', "?filter.hosts.1=host-77");

    $url = ClassNetwork::getUriWithoutParam();
    ClassVMwareTool::getLoginAndSetCookieFileVCenter($domain, $un, $pw);


    //echo "<br/>\n xxx= " . ctoolUrl::getUrlRequestUri();

    $vmId = 0;

    if (isset($params['vmid'])) {
        $vmId = $params['vmid'];
        $ret = ClassVMwareTool::getWebTokenMks($domain, $vmId);
        $domainVM = $ret[0];
        $ticket = $ret[1];
    }

    ?>


    <div class="page-container">
        <div class="panel-container">
            <div class="panel-left">
                <div id="left_vm_list"
                     style="max-height: 600px; overflow-x: hidden; overflow-y:auto; border-bottom: 1px solid #ccc ">
                    <?php
                    foreach ($vmList as $item) {
                        if ($item instanceof ClassVMinfo) {
                            $url = ctoolUrl::setUrlParam(ctoolUrl::getUrlRequestUri(), "vmid", $item->vm);
                            $padBorder = '';
                            if (isset($params['vmid']) && $params['vmid'] == $item->vm)
                                $padBorder = 'font-weight: bolder; color: brown';

                            $padOn = "<div style='display: inline-block; width: 10px; height: 10px; background-color: green; border-radius: 5px'> </div>";
                            if($item->isOff()){
                                $padOn = "<div style='display: inline-block; width: 10px; height: 10px; background-color: grey; border-radius: 5px'> </div>";
                            }
                            echo " <a href='#' onclick='jclsVmCtrl.updateNewVM(\"$item->vm\", \"vm_id_in_div_$item->vm\")' title='$item->name' style='$padBorder' id='vm_id_in_div_$item->vm'> $padOn $item->name </a> <br> ";
                        }
                    }
                    ?>
                    <br><br><br><br><br><br><br><br><br><br><br>
                    <br><br><br><br><br><br><br><br><br><br><br>
                </div>

                <?php
                echo " Total VM: " . count($vmList);
                ?>
            </div>
            <div class="splitter"></div>
            <div class="panel-right">
                <!--                <button onclick="updateSc()"> updateScreen After resize</button>-->
                <div id="vmGlxContainer"
                     style="position:relative; width:1024px;height:700px; border: 1px solid #ccc"></div>
                <div style="text-align: center">
                    <button onclick="jclsVmCtrl.updateNewVM('', '')"> Refresh</button>
                    <button onclick="jclsVmCtrl.sendCtrlAltDel()"> Ctrl+Alt+Del</button>
                    <button onclick="jclsVmCtrl.vmPowerOn()"> PowerOn</button>
                    <button onclick="jclsVmCtrl.vmPowerOff()"> PowerOff</button>
                    <button onclick="jclsVmCtrl.vmPowerReset()"> Reset</button>
                    <button onclick="jclsVmCtrl.vmSetBootFromCD(1)"> SetBootFromCD</button>
                    <button onclick="jclsVmCtrl.vmSetBootFromDisk(1)"> SetBootFromDisk</button>
                </div>
            </div>
        </div>

    </div>
    <!--<div id="vmGlxContainer" style="position:relative;width:100%;height:80%; border: 2px solid red"></div>-->

    <div style="clear: both"></div>


    <script src='/public/js/jquery-resizable.js'></script>

    <script id="rendered-js">
        $(".panel-left").resizable({
            handleSelector: ".splitter",
            resizeHeight: false
        });

        $(".panel-top").resizable({
            handleSelector: ".splitter-horizontal",
            resizeWidth: false
        });
        //# sourceURL=pen.js
    </script>

    <?php
    if (($vmId)) {
        ?>
        <script>
            var myElement = document.getElementById('vm_id_in_div_<?php echo $vmId ?>');
            var topPos = myElement.offsetTop - 50;
            document.getElementById('left_vm_list').scrollTop = topPos;
        </script>
        <?php
    }

    ?>

    <?php

    _END:

    ?>

</section>
