<?php
$mm = [
    "index" => "<i class='fa fa-list'></i> &nbsp; Danh sách Khối giao diện",
];

?>

<div class="content-header header_menu_news" style="padding-top: 20px">
    <a style="color: #337ab7; font-weight: bold" class="form-control" href="/admin/setting-ui">
        <i class="fa fa-list"></i> &nbsp; Danh sách Khối giao diện       </a>
</div>

<br>
<p style="border-bottom: 1px solid #ccc; margin: 0px"></p>

