<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Monitor
        <small>list</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Monitor list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content" ng-controller="monitor_server_view">

    <?php
    require_once "application/block/default_index.php";
    ?>

</section>
<!-- /.content -->
<!-- Main content -->