<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Đơn hàng
        <small>Danh sách</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">đơn hàng</li>
    </ol>
</section>

<!-- Main content -->
<section class="content" ng-controller="admin_bill_center_index">

    <?php
    require_once "application/block/default_index.php";
    ?>

</section>
<!-- /.content -->
<!-- Main content -->